#if !canImport(ObjectiveC)
import XCTest

extension HelloWorldTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HelloWorldTests = [
        ("testMissingLambdaRuntimeApi", testMissingLambdaRuntimeApi),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HelloWorldTests.__allTests__HelloWorldTests),
    ]
}
#endif
