#if !canImport(ObjectiveC)
import XCTest

extension S3TestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__S3TestTests = [
        ("testMissingLambdaRuntimeApi", testMissingLambdaRuntimeApi),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(S3TestTests.__allTests__S3TestTests),
    ]
}
#endif
