#if !canImport(ObjectiveC)
import XCTest

extension HTTPSRequestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTTPSRequestTests = [
        ("testMissingLambdaRuntimeApi", testMissingLambdaRuntimeApi),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HTTPSRequestTests.__allTests__HTTPSRequestTests),
    ]
}
#endif
