# Note: This must be launched from the root path
SWIFT_PROJECT_PATH=Examples/HTTPSRequest

start_docker_compose_env:
	cd $(SWIFT_PROJECT_PATH); docker-compose up -d ; sleep 5

stop_docker_compose_env:
	cd $(SWIFT_PROJECT_PATH); docker-compose stop